name: Trigger-Localisation-Builds

on:
  workflow_dispatch:
     inputs:
      Language:
        description: "Select All languages to build"
        required: false
        type: choice
        options:
         - ALL
         - SINGLE
      BUILD_TYPE:
        description: "Select individual language to build"
        required: true
        type: choice
        options:
          - main
          - lts
          - build
      COUNTRY:
        description: "Select individual language to build"
        required: false
        type: choice
        options:
          - PT-BR
          - DE
          - ES
          - FR
          - IT
          - JA
          - KO
          - PL
          - RU
          - ZH    

jobs:

  Trigger-Localisation-Builds:
     name:
     runs-on: ubuntu-22.04
     strategy:
      matrix:
        language: [PT-BR, DE, ES, FR, IT, JA, KO, PL, RU, ZH]
     steps:
      - name: Invoke Localisation Workflows
        if: ${{ github.event.inputs.Language }} == 'ALL'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ github.event.inputs.BUILD_TYPE }}.yml
          repo: YoYoGames/GameMaker-Manual-${{ matrix.language }}
          token: ${{ secrets.GH_TOKEN }} 
        continue-on-error: false 
      - name: Invoke Localisation Workflows
        if: ${{ github.event.inputs.Language }} == 'SINGLE'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ github.event.inputs.BUILD_TYPE }}.yml
          repo: YoYoGames/GameMaker-Manual-${{ github.event.inputs.COUNTRY }}
          token: ${{ secrets.GH_TOKEN }} 
        continue-on-error: false         


                                                                       